#!/bin/bash


# auxilliary function to add a ppa only if it exists
add_ppa() {
  grep -h "^deb.*$1" /etc/apt/sources.list.d/* > /dev/null 2>&1
  if [ $? -ne 0 ]
  then
    echo "Adding ppa:$1"
    add-apt-repository -y ppa:$1
    return 0
  fi

  echo "ppa:$1 already exists"
  return 1
}

. /etc/lsb-release

if [ "$DISTRIB_RELEASE" == "14.04" ]; then
add_ppa irie/blender #Blender
apt-get update
cd ubuntu_14.04
echo "14.04"
fi

if [ "$DISTRIB_RELEASE" == "17.3" ]; then
add_ppa irie/blender #Blender
apt-get update
cd ubuntu_14.04
echo "14.04"
fi

if [ "$DISTRIB_RELEASE" == "16.04" ]; then
cd ubuntu_16.04
echo "16.04"
fi

if [ ! -e dependencies ]; then
exit 1
fi

while read line
do
apt-get -fy install $line > /dev/null
if [ $? == 0 ]; then
echo " " $line installed
fi
done <"dependencies"

sudo gdebi -n libcollada-dev.deb
sudo gdebi -n libvrpn-dev.deb
sudo gdebi -n libopensg-dev.deb
sudo gdebi -n libvirtuose-dev.deb
sudo gdebi -n libcef-dev.deb
sudo gdebi -n libstepcode-dev.deb
# sudo gdebi -n polyvr.deb


